let tanh1 = '<math>\n' +
    '  <mi>tanh (&#119909;) = </mi>\n' +
    '  <mfrac>\n' +
    '    <msup>\n' +
    '      <mi>sinh(&#119909;)</mi>\n' +
    '    </msup>\n' +
    '    <msup>\n' +
    '      <mi>cosh(&#119909;)</mi>\n' +
    '    </msup>\n' +
    '  </mfrac>\n' +
    '  <mo>=</mo>\n' +
    '  <mfrac>\n' +
    '    <mrow>\n' +
    '          <msup>\n' +
    '              <mi>e</mi>\n' +
    '              <mn>&#119909;</mn>\n' +
    '            </msup>\n' +
    '            <mo>-</mo>\n' +
    '            <msup>\n' +
    '              <mi>e</mi>\n' +
    '              <mn>-&#119909;</mn>\n' +
    '            </msup>\n' +
    '          </mrow>\n' +
    '      <mrow>\n' +
    '          <msup>\n' +
    '            <mi>e</mi>\n' +
    '            <mn>&#119909;</mn>\n' +
    '          </msup>\n' +
    '        <mo>+</mo>\n' +
    '        <msup>\n' +
    '          <mi>e</mi>\n' +
    '          <mn>-&#119909;</mn>\n' +
    '        </msup>\n' +
    '    </mrow>\n' +
    '    </mfrac>\n' +
    '  <mo>=</mo>\n' +
    '  <mfrac>\n' +
    '    <mrow>\n' +
    '          <msup>\n' +
    '              <mi>e</mi>\n' +
    '              <mn>2&#119909;</mn>\n' +
    '            </msup>\n' +
    '            <mo>-</mo>\n' +
    '            <msup>\n' +
    '              <mi>1</mi>\n' +
    '            </msup>\n' +
    '          </mrow>\n' +
    '      <mrow>\n' +
    '          <msup>\n' +
    '            <mi>e</mi>\n' +
    '            <mn>2&#119909;</mn>\n' +
    '          </msup>\n' +
    '        <mo>+</mo>\n' +
    '        <msup>\n' +
    '          <mi>1</mi>\n' +
    '        </msup>\n' +
    '    </mrow>\n' +
    '    </mfrac>\n' +
    '      </math>';
document.getElementById("tanH1").innerHTML = tanh1;